# Generated by Django 5.2 on 2025-05-01 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_cate', models.CharField(max_length=50)),
                ('desc_cate', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_produc', models.CharField(max_length=50, unique=True)),
                ('des_produc', models.TextField()),
                ('unidad_produc', models.CharField(max_length=10)),
                ('exist_produc', models.IntegerField(null=True)),
                ('stock_produc', models.IntegerField()),
                ('precio_produc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appCatalogo.categorias')),
            ],
        ),
    ]
